export const UPDATE_USER = 'USER/UPDATE'
export const REMOVE_USER = 'USER/REMOVE'
export const SIGN_IN_ROLE_CHANGE = 'SIGN_IN_ROLE_CHANGE'
export const UPDATE_AUTH = 'UPDATE_AUTH'


export const UPDATE_CUSTOMERS = 'USER/UPDATE_CUSTOMERS'
export const UPDATE_PERFORMERS = 'USER/UPDATE_PERFORMERS'
export const UPDATE_NEW_TASKS = 'TASK/UPDATE_NEW_TASKS'
export const UPDATE_CURRENT_WORKING_TASK = 'TASK/UPDATE_CURRENT_TASK'
export const UPDATE_WORKING_TASKS = 'TASK/UPDATE_WORKING_TASKS'
